/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TTS_H
#define TTS_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "tts_profile_types.h"

namespace something {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TTSIf {
 public:
  virtual ~TTSIf() {}
  virtual void genAudio(std::string& _return, const std::string& text) = 0;
};

class TTSIfFactory {
 public:
  typedef TTSIf Handler;

  virtual ~TTSIfFactory() {}

  virtual TTSIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TTSIf* /* handler */) = 0;
};

class TTSIfSingletonFactory : virtual public TTSIfFactory {
 public:
  TTSIfSingletonFactory(const boost::shared_ptr<TTSIf>& iface) : iface_(iface) {}
  virtual ~TTSIfSingletonFactory() {}

  virtual TTSIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TTSIf* /* handler */) {}

 protected:
  boost::shared_ptr<TTSIf> iface_;
};

class TTSNull : virtual public TTSIf {
 public:
  virtual ~TTSNull() {}
  void genAudio(std::string& /* _return */, const std::string& /* text */) {
    return;
  }
};

typedef struct _TTS_genAudio_args__isset {
  _TTS_genAudio_args__isset() : text(false) {}
  bool text :1;
} _TTS_genAudio_args__isset;

class TTS_genAudio_args {
 public:

  TTS_genAudio_args(const TTS_genAudio_args&);
  TTS_genAudio_args& operator=(const TTS_genAudio_args&);
  TTS_genAudio_args() : text() {
  }

  virtual ~TTS_genAudio_args() throw();
  std::string text;

  _TTS_genAudio_args__isset __isset;

  void __set_text(const std::string& val);

  bool operator == (const TTS_genAudio_args & rhs) const
  {
    if (!(text == rhs.text))
      return false;
    return true;
  }
  bool operator != (const TTS_genAudio_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTS_genAudio_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TTS_genAudio_pargs {
 public:


  virtual ~TTS_genAudio_pargs() throw();
  const std::string* text;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TTS_genAudio_result__isset {
  _TTS_genAudio_result__isset() : success(false) {}
  bool success :1;
} _TTS_genAudio_result__isset;

class TTS_genAudio_result {
 public:

  TTS_genAudio_result(const TTS_genAudio_result&);
  TTS_genAudio_result& operator=(const TTS_genAudio_result&);
  TTS_genAudio_result() : success() {
  }

  virtual ~TTS_genAudio_result() throw();
  std::string success;

  _TTS_genAudio_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TTS_genAudio_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TTS_genAudio_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTS_genAudio_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TTS_genAudio_presult__isset {
  _TTS_genAudio_presult__isset() : success(false) {}
  bool success :1;
} _TTS_genAudio_presult__isset;

class TTS_genAudio_presult {
 public:


  virtual ~TTS_genAudio_presult() throw();
  std::string* success;

  _TTS_genAudio_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TTSClient : virtual public TTSIf {
 public:
  TTSClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TTSClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void genAudio(std::string& _return, const std::string& text);
  void send_genAudio(const std::string& text);
  void recv_genAudio(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TTSProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<TTSIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TTSProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_genAudio(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TTSProcessor(boost::shared_ptr<TTSIf> iface) :
    iface_(iface) {
    processMap_["genAudio"] = &TTSProcessor::process_genAudio;
  }

  virtual ~TTSProcessor() {}
};

class TTSProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TTSProcessorFactory(const ::boost::shared_ptr< TTSIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TTSIfFactory > handlerFactory_;
};

class TTSMultiface : virtual public TTSIf {
 public:
  TTSMultiface(std::vector<boost::shared_ptr<TTSIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TTSMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TTSIf> > ifaces_;
  TTSMultiface() {}
  void add(boost::shared_ptr<TTSIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void genAudio(std::string& _return, const std::string& text) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->genAudio(_return, text);
    }
    ifaces_[i]->genAudio(_return, text);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TTSConcurrentClient : virtual public TTSIf {
 public:
  TTSConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TTSConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void genAudio(std::string& _return, const std::string& text);
  int32_t send_genAudio(const std::string& text);
  void recv_genAudio(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
