/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tts_profile_CONSTANTS_H
#define tts_profile_CONSTANTS_H

#include "tts_profile_types.h"

namespace something {

class tts_profileConstants {
 public:
  tts_profileConstants();

};

extern const tts_profileConstants g_tts_profile_constants;

} // namespace

#endif
