/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tts_profile_constants.h"

namespace something {

const tts_profileConstants g_tts_profile_constants;

tts_profileConstants::tts_profileConstants() {
}

} // namespace

